config/routes.rb
Rails.application.routes.draw do
  resources :emprunts
  resources :materiels
  resources :documents
  resources :auteurs
  resources :adherents
  get 'home/index'
  root 'home#index'

  get "/searchAd" => "adherents#index", :as => :search_ad 
  get "/searchDoc" => "documents#index", :as => :search_doc 
  get "/searchAuth" => "auteurs#index", :as => :search_auth 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/home/navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-dark">

<%= link_to root_path do %>
   <%= image_tag "Biblio.jpeg", style: "width: 40px" %>
<% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse sidenav" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <%= link_to "Adherent", adherents_path, class:"nav-link text-light" 
        %>
        </li>
         <li class="nav-item">
        <%= link_to "Documents", documents_path, class:"nav-link text-light" %>
        </li>
        <li class="nav-item">
        <%= link_to "Auteurs", auteurs_path, class:"nav-link text-light" %>
        </li>
        <li class="nav-item">
        <%= link_to "Materiel", materiels_path, class:"nav-link text-light" %>
        </li>
        <li class="nav-item">
        <%= link_to "Emprunts", emprunts_path, class:"nav-link text-light" %>
        </li>
      </ul>
    </div>
  </nav>