config/routes.rb
Rails.application.routes.draw do
  resources :emprunts
  resources :materiels
  resources :documents
  resources :auteurs
  resources :adherents
  get 'home/index'
  root 'home#index'

  get "/searchAd" => "adherents#index", :as => :search_ad 
  get "/searchDoc" => "documents#index", :as => :search_doc 
  get "/searchAuth" => "auteurs#index", :as => :search_auth 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/document.rb
class Document < ApplicationRecord
    # has_many :auteurs, class_name: "auteur"
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]
  $document_auteurs = []
  $query = ''

  # GET /documents or /documents.json
  def index
    if(params[:query].nil?)
      @documents = Document.all
      return
    end

    query = params[:query]
    @documents = search(query)
  end

  # GET /documents/1 or /documents/1.json
  def show
    id = request.url.split("/")[4]
    @auteurs = getDocumentAuteurs(id)
  end

  # GET /documents/new
  def new
    @is_edit = false
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @is_edit = true
    @auteurs = getAuteurs()
  end

  def getDocumentAuteurs(id)
    document_auteurs = Auteur.all.joins("LEFT JOIN document_auteurs ON auteurs.id=document_auteurs.auteur_id").where("document_auteurs.document_id=:id", id: Integer(id))
    # ids = document_auteurs.map{ |auteur| auter.aut}
    return document_auteurs
  end

  def getAuteurs()
    return Auteur.all
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)
    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end
  def search(query)
    res = Document.all.where("lower(titre) LIKE :search", search:"%#{query}%")
    return res
  end


  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|

      id = params[:auteur_id]
     
      if(id)
        inserts = [@document.id, id]
        sql = "INSERT INTO document_auteurs('document_id', 'auteur_id') VALUES(#{inserts.join(", ")})"
        ActiveRecord::Base.connection.execute(sql) 
      end
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:doc_type, :titre, :isbn)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<tr id="<%= dom_id document %>">
  <th scope="row">
    <%= document.id %>
  </th>
  <td>
    <%= document.doc_type %>
  </td>
  <td>
    <%= document.titre %>
  </td>
  <td>
    <%= document.isbn %>
  </td>
  <td>
    <%= document.created_at.strftime("%Y-%m-%d %H:%M") %>
  </td>
  <td>
    <%= button_to "", document, class:"btn btn-outline-primary bi bi-eye", :method => "get" %>
  </td>
</tr>

app/views/documents/_form.html.erb
  <%= form_with(model: document) do |form| %>
<div class="d-flex mt-5 align-items-start " >
  <div class="mr-3 w-100" >

  <%if @is_edit%>
  <h1 class="mb-3" >Editing document</h1>
  <%else%>
  <h1 class="mb-3" >Nouveau document</h1>

  <%end%>
    <% if document.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

        <ul>
          <% document.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="input-group mb-3">
          <div class="input-group-prepend">
              <%= form.label :doc_type, class: "input-group-text"  %>
            <%= form.text_field :doc_type, class: "form-control" %>
          </div>
    </div>

    <div class="input-group mb-3">
          <div class="input-group-prepend">
              <%= form.label :titre, class: "input-group-text"  %>
            <%= form.text_field :titre, class: "form-control" %>
          </div>
    </div>
  
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <%= form.label :isbn, class: "input-group-text"  %>
          <%= form.text_field :isbn, class: "form-control" %>
        </div>
    </div>
  </div>

  <%if @is_edit%>
  <div class="w-100" >
    <h1 class="mb-3">Ajouter un auteur</h1>
     <%= select_tag(:auteur_id, options_for_select( [["Selectioner un auteur", 0]] +  @auteurs.map{ |auteur| [auteur.nom_prenom, auteur.id]}), class:"custom-select form-select form-select-lg") %>
  </div>

  <% end %>
  
    </div>
      <%= form.submit %>
  <% end %>
  
</div>

app/views/documents/edit.html.erb
<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="mt-5">

<div class="d-flex justify-content-between align-items-center mb-5">
  <h1 class="mb-0 pb-0" >Documents</h1>
  <%= button_to "", new_document_path, class:"btn btn-outline-primary bi bi-plus", :method => "get" %>
</div>
  <div class="mb-5 d-flex justify-content-betweeb">
      <input id="search" class="form-control mr-sm-2" type="search" placeholder="Chercher par titre" aria-label="Search">
      <button style="display:none" id="search_btn" class="btn btn-outline-primary" >Search</button>
  </div>


  <div id="documents">

    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">type</th>
          <th scope="col">Titre</th>
          <th scope="col">isbn</th>
          <th scope="col">Created</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @documents.each do |document| %>
        <%= render document %>
      <% end %>
      </tbody>
    </table>

</div>




<script>
 $(document).ready(function(){
  $("#search").val(<%$query%>)
  let timeout;
  $("#search").keyup(function(){
    clearTimeout(timeout)
    timeout = setTimeout(() => {
         let q = $("#search").val()
    $.ajax({
      type: "GET",
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      url: "/searchDoc",
      data: {query : q.trim()},
      success: function(response) {
              $('body').html(response);
              $("#search").val(q)
              $("#search").focus()
        }
      })
    }, 400);
    });

});
</script>

app/views/documents/new.html.erb
<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/show.html.erb
<div class="container mt-5">
  <div class="mb-5" >
    <div class="d-flex w-100 mb-2">
        <div class="w-25">ID:</div>
        <div><strong><%= @document.id %></strong> </div>
      </div>

    <div class="d-flex w-100 mb-2">
      <div class="w-25">Nom:</div>
      <div><strong><%= @document.doc_type %></strong> </div>
    </div>

    <div class="d-flex w-100 mb-2">
      <div class="w-25">Prenom:</div>
      <div><strong><%= @document.titre %></strong> </div>
    </div>

     <div class="d-flex w-100 mb-2">
      <div class="w-25">Prenom:</div>
      <div><strong><%= @document.isbn %></strong> </div>
    </div>
    
    <div class="d-flex w-100 mb-2">
      <div class="w-25">Auteurs:</div>
      <div><strong><% @auteurs.each do |auteur| %>
        <%= "#{auteur.nom_prenom}, " %>
      <% end %></strong></div>
    </div>

  </div>
  <div class="mb-2" >
     <%= link_to "Edit this document", edit_document_path(@document) %> |
      <%= link_to "Back to documents", documents_path %>
  </div>
   

    <%= button_to "Destroy this document", @document, method: :delete, class: "btn btn-outline-danger" %>
</div>