config/routes.rb
Rails.application.routes.draw do
  resources :emprunts
  resources :materiels
  resources :documents
  resources :auteurs
  resources :adherents
  get 'home/index'
  root 'home#index'

  get "/searchAd" => "adherents#index", :as => :search_ad 
  get "/searchDoc" => "documents#index", :as => :search_doc 
  get "/searchAuth" => "auteurs#index", :as => :search_auth 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/adherent.rb
class Adherent < ApplicationRecord
end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  before_action :set_adherent, only: %i[ show edit update destroy ]
  $search_triggered = false
  $adherents = []
  $query = ''
  # def initialize()
  #   @search_triggered = false
  # end

  # GET /adherents or /adherents.json
  def index

    if(params[:query].nil?)
      $adherents = Adherent.all
      return
    end

    query = params[:query]
    $adherents = search(query)
  end

  # GET /adherents/1 or /adherents/1.json
  def show
  end

  # GET /adherents/new
  def new
    @adherent = Adherent.new
  end

  # GET /adherents/1/edit
  def edit
  end

  # POST /adherents or /adherents.json
  def create
    @adherent = Adherent.new(adherent_params)

    respond_to do |format|
      if @adherent.save
        format.html { redirect_to adherents_url, notice: "Adherent was successfully created." }
        format.json { render :show, status: :created, location: @adherent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end

    end
  end


  def search(query)
    res = Adherent.all.where("lower(nom) LIKE :search", search:"%#{query}%")
    return res
  end

  # PATCH/PUT /adherents/1 or /adherents/1.json
  def update
    respond_to do |format|
      if @adherent.update(adherent_params)
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully updated." }
        format.json { render :show, status: :ok, location: @adherent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adherents/1 or /adherents/1.json
  def destroy
    @adherent.destroy

    respond_to do |format|
      format.html { redirect_to adherents_url, notice: "Adherent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adherent
      @adherent = Adherent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adherent_params
      params.require(:adherent).permit(:nom, :prenom, :id)
    end
end

app/helpers/adherents_helper.rb
module AdherentsHelper
end

app/views/adherents/_adherent.html.erb
<tr id="<%= dom_id adherent %>">
  <th scope="row">
    <%= adherent.id %>
  </th>
  <td>
    <%= adherent.nom %>
  </td>
  <td>
    <%= adherent.prenom %>
  </td>
  <td>
    <%= adherent.created_at.strftime("%Y-%m-%d %H:%M") %>
  </td>
  <td>
    <%= button_to "", adherent, class:"btn btn-outline-primary bi bi-eye", :method => "get" %>
  </td>
</tr>

app/views/adherents/_form.html.erb
<div class="mt-5">
  <%= form_with(model: adherent) do |form| %>
    <% if adherent.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(adherent.errors.count, "error") %> prohibited this adherent from being saved:</h2>

        <ul>
          <% adherent.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="mb-4">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
            <%= form.label :nom, class: "input-group-text"  %>
          <%= form.text_field :nom, class: "form-control" %>
        </div>
      </div>

      <div class="input-group mb-3">
        <div class="input-group-prepend">
            <%= form.label :prenom, class: "input-group-text"  %>
          <%= form.text_field :prenom, class: "form-control" %>
        </div>
      </div>
  </div>

      <%= form.submit class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/adherents/edit.html.erb
<h1>Editing adherent</h1>

<%= render "form", adherent: @adherent %>

<br>

<div>
  <%= link_to "Show this adherent", @adherent %> |
  <%= link_to "Back to adherents", adherents_path %>
</div>

app/views/adherents/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="mt-5">

<div class="d-flex justify-content-between align-items-center mb-5">
  <h1 class="mb-0 pb-0" >Adherents</h1>
  <%= button_to "", new_adherent_path, class:"btn btn-outline-primary bi bi-plus", :method => "get" %>
</div>
  <div class="mb-5 d-flex justify-content-betweeb">
      <input id="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button style="display:none" id="search_btn" class="btn btn-outline-primary" >Search</button>
  </div>


  <div id="adherents">

    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nom</th>
          <th scope="col">Prenom</th>
          <th scope="col">Created</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% $adherents.each do |adherent| %>
        <%= render adherent %>
      <% end %>
      </tbody>
    </table>

  
</div>


<script>
 $(document).ready(function(){
  $("#search").val(<%$query%>)
  let timeout;
  $("#search").keyup(function(){
    clearTimeout(timeout)
    timeout = setTimeout(() => {
         let q = $("#search").val()
    $.ajax({
      type: "GET",
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      url: "/searchAd",
      data: {query : q.trim()},
      success: function(response) {
              $('body').html(response);
              $("#search").val(q)
              $("#search").focus()
        }
      })
    }, 400);
    });

});
</script>

app/views/adherents/new.html.erb
<div class="h1">New adherent</div>

<%= render "form", adherent: @adherent %>

<br>

<div>
  <%= link_to "Back to adherents", adherents_path %>
</div>

app/views/adherents/show.html.erb
<div class="container mt-5">
  <div class="mb-5" >
    <div class="d-flex w-100 mb-2">
        <div class="w-25">ID:</div>
        <div><strong><%= @adherent.id %></strong> </div>
      </div>

    <div class="d-flex w-100 mb-2">
      <div class="w-25">Nom:</div>
      <div><strong><%= @adherent.nom %></strong> </div>
    </div>

    <div class="d-flex w-100 mb-2">
      <div class="w-25">Prenom:</div>
      <div><strong><%= @adherent.prenom %></strong> </div>
    </div>
  </div>
  <div class="mb-2" >
     <%= link_to "Edit this adherent", edit_adherent_path(@adherent) %> |
      <%= link_to "Back to adherents", adherents_path %>
  </div>
   

    <%= button_to "Destroy this adherent", @adherent, method: :delete, class: "btn btn-outline-danger" %>
</div>