config/routes.rb
Rails.application.routes.draw do
  resources :emprunts
  resources :materiels
  resources :documents
  resources :auteurs
  resources :adherents
  get 'home/index'
  root 'home#index'

  get "/searchAd" => "adherents#index", :as => :search_ad 
  get "/searchDoc" => "documents#index", :as => :search_doc 
  get "/searchAuth" => "auteurs#index", :as => :search_auth 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/materiel.rb
class Materiel < ApplicationRecord
end

app/controllers/materiels_controller.rb
class MaterielsController < ApplicationController
  before_action :set_materiel, only: %i[ show edit update destroy ]

  # GET /materiels or /materiels.json
  def index
    @materiels = Materiel.all
  end

  # GET /materiels/1 or /materiels/1.json
  def show
  end

  # GET /materiels/new
  def new
    @materiel = Materiel.new
  end

  # GET /materiels/1/edit
  def edit
  end

  # POST /materiels or /materiels.json
  def create
    @materiel = Materiel.new(materiel_params)

    respond_to do |format|
      if @materiel.save
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully created." }
        format.json { render :show, status: :created, location: @materiel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materiels/1 or /materiels/1.json
  def update
    respond_to do |format|
      if @materiel.update(materiel_params)
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully updated." }
        format.json { render :show, status: :ok, location: @materiel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materiels/1 or /materiels/1.json
  def destroy
    @materiel.destroy

    respond_to do |format|
      format.html { redirect_to materiels_url, notice: "Materiel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materiel
      @materiel = Materiel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def materiel_params
      params.require(:materiel).permit(:mat_type, :nom)
    end
end

app/helpers/materiels_helper.rb
module MaterielsHelper
end

app/views/materiels/_form.html.erb
<%= form_with(model: materiel) do |form| %>
  <% if materiel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(materiel.errors.count, "error") %> prohibited this materiel from being saved:</h2>

      <ul>
        <% materiel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :mat_type, style: "display: block" %>
    <%= form.text_field :mat_type %>
  </div>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

    <div class="mt-3" >
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/materiels/_materiel.html.erb
<div id="<%= dom_id materiel %>">
  <th scope="row">
    <%= materiel.id %>
  </th>
  <td>
    <%= materiel.mat_type %>
  </td>
  <td>
    <%= materiel.nom %>
  </td>
  <td>
    <%= materiel.created_at.strftime("%Y-%m-%d %H:%M") %>
  </td>
  <td>
    <%= button_to "", materiel, class:"btn btn-outline-primary bi bi-eye", :method => "get" %>
  </td>
</tr>


</div>

app/views/materiels/edit.html.erb
<h1>Editing materiel</h1>

<%= render "form", materiel: @materiel %>

<br>

<div>
  <%= link_to "Show this materiel", @materiel %> |
  <%= link_to "Back to materiels", materiels_path %>
</div>

app/views/materiels/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center mt-5 mb-5">
  <h1 class="mb-0 pb-0" >Materiels</h1>
  <%= button_to "", new_materiel_path, class:"btn btn-outline-primary bi bi-plus", :method => "get" %>
</div>

<div id="materiels">
<table class="table" >
  <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Type</th>
          <th scope="col">Nom</th>
          <th scope="col">Created</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @materiels.each do |materiel| %>
        <%= render materiel %>
      <% end %>
      </tbody>
    </table>

</div>

<%= link_to "New materiel", new_materiel_path %>

app/views/materiels/new.html.erb
<h1>New materiel</h1>

<%= render "form", materiel: @materiel %>

<br>

<div>
  <%= link_to "Back to materiels", materiels_path %>
</div>

app/views/materiels/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="mb-5 mt-5">
  <%= link_to "Modifier ce materiel", edit_materiel_path(@materiel) %> |
  <%= link_to "Retour vers materiels", materiels_path %>
</div>

<div class="mb-5 mt-5" >
    <div class="d-flex w-100 mb-2">
        <div class="w-25">ID:</div>
        <div><strong><%= @materiel.id %></strong> </div>
      </div>

      <div class="d-flex w-100 mb-2">
        <div class="w-25">Nom:</div>
        <div><strong><%= @materiel.nom %></strong> </div>
      </div>

      <div class="d-flex w-100 mb-2">
        <div class="w-25">Ajouté:</div>
        <div><strong><%= @materiel.created_at.strftime("%Y-%m-%d %H:%M")  %></strong> </div>
      </div>

<div class="mb-2 mt-5">


  <%= button_to "Supprimer ce materiel", @materiel, method: :delete, class: "btn btn-outline-danger" %>
</div>

</div>